// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4JnP6PYZ6UoELCM_dPSUP--IRHIYzzQ4',
    appId: '1:43440781583:web:7508ab74ad3c3ba61aa67a',
    messagingSenderId: '43440781583',
    projectId: 'sanskriti-by-okay-anshu',
    authDomain: 'sanskriti-by-okay-anshu.firebaseapp.com',
    storageBucket: 'sanskriti-by-okay-anshu.appspot.com',
    measurementId: 'G-R9TKD5G6F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwhUYTazWVbnUhD2PbgQ-PxKHPviMD3Zc',
    appId: '1:43440781583:android:3334a448a63bc7351aa67a',
    messagingSenderId: '43440781583',
    projectId: 'sanskriti-by-okay-anshu',
    storageBucket: 'sanskriti-by-okay-anshu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV1HGwTbVfGxLrtAL19av1RX4UKutqc3I',
    appId: '1:43440781583:ios:b61034399b4dd4ca1aa67a',
    messagingSenderId: '43440781583',
    projectId: 'sanskriti-by-okay-anshu',
    storageBucket: 'sanskriti-by-okay-anshu.appspot.com',
    iosBundleId: 'com.example.sanskriti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV1HGwTbVfGxLrtAL19av1RX4UKutqc3I',
    appId: '1:43440781583:ios:aac0d0d93b5a38361aa67a',
    messagingSenderId: '43440781583',
    projectId: 'sanskriti-by-okay-anshu',
    storageBucket: 'sanskriti-by-okay-anshu.appspot.com',
    iosBundleId: 'com.example.sanskriti.RunnerTests',
  );
}
